groups:
- name: be_servers_alert
  rules:
  - alert: be_servers_no_backends
    expr: haproxy_backend_active_servers{proxy="backend_servers"} < 1
    for: 15s
    labels:
      severity: page      
    annotations:
      summary: HAProxy reports all servers are unhealthy for be_app.
 
  - alert: test_server_500
    expr: rate(haproxy_backend_http_responses_total{proxy= 'backend_servers',code='5xx'}[5m]) > 0
    for: 15s
    labels:
      serverity: page
    annotations:
      summary: The server at test.ianleedham.dev is down
    
